# Generated by Django 6.0.6 on 2026-08-18 14:00

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import users.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('full_name', models.CharField(max_length=250)),
                ('email', models.CharField(max_length=100, unique=True, validators=[users.models.validate_email])),
                ('password', models.CharField(blank=True, db_column='password', max_length=250, null=True)),
                ('role', models.CharField(blank=True, choices=[('admin', 'Admin'), ('coach', 'Coach'), ('player', 'Player')], db_column='rol', max_length=10, null=True)),
                ('gender', models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female')], max_length=10, null=True)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('auth_provider', models.CharField(blank=True, choices=[('local', 'Local'), ('google', 'Google')], default='local', max_length=50, null=True)),
                ('provider_user_id', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.BooleanField(db_column='status', default=False)),
                ('created_at', models.DateTimeField(blank=True, db_column='creat_at', default=django.utils.timezone.now, null=True)),
            ],
            options={
                'db_table': 'Users',
            },
        ),
        migrations.CreateModel(
            name='AdminProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(blank=True, db_column='user_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='admin_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Admin_Profiles',
            },
        ),
        migrations.CreateModel(
            name='CoachProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specialization', models.CharField(blank=True, choices=[('Bodybuilding', 'Bodybuilding'), ('PowerLifting', 'PowerLifting'), ('Both', 'Both')], max_length=50, null=True)),
                ('experience_years', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('bio', models.CharField(blank=True, max_length=500, null=True)),
                ('image_profile_url', models.ImageField(blank=True, null=True, upload_to='profiles/')),
                ('verification_status', models.CharField(blank=True, choices=[('waiting', 'Waiting'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], max_length=50, null=True)),
                ('instagram_url', models.CharField(blank=True, max_length=255, null=True)),
                ('facebook_url', models.CharField(blank=True, max_length=255, null=True)),
                ('whatsapp_url', models.CharField(blank=True, max_length=255, null=True)),
                ('youtube_url', models.CharField(blank=True, max_length=255, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='update_at')),
                ('user', models.OneToOneField(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='coach_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Coach_Profiles',
            },
        ),
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificate_pdf_url', models.FileField(blank=True, null=True, upload_to='certificates/')),
                ('verification_status', models.CharField(blank=True, choices=[('waiting', 'Waiting'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], max_length=50, null=True)),
                ('rejection_reason', models.CharField(blank=True, choices=[('Certificate photo is unclear / Serial number not visible', 'Certificate photo is unclear / Serial number not visible'), ('Invalid or forged credentials', 'Invalid or forged credentials'), ('Other', 'Other')], max_length=500, null=True)),
                ('note', models.CharField(blank=True, max_length=500, null=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_verifications', to=settings.AUTH_USER_MODEL)),
                ('coach_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to='users.coachprofile')),
            ],
        ),
        migrations.CreateModel(
            name='CoachTransformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('before_image_url', models.ImageField(upload_to='coach_album/')),
                ('after_image_url', models.ImageField(upload_to='coach_album/')),
                ('duration', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('coach', models.ForeignKey(db_column='coach_id', on_delete=django.db.models.deletion.CASCADE, related_name='transformations', to='users.coachprofile')),
            ],
            options={
                'db_table': 'Coach_Transformations',
            },
        ),
        migrations.CreateModel(
            name='Otp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('otp_code', models.CharField(max_length=6)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('expires_at', models.DateTimeField()),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='otps', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Otps',
            },
        ),
        migrations.CreateModel(
            name='PlayerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('training_age_years', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('image_profile_url', models.ImageField(blank=True, null=True, upload_to='profiles/')),
                ('weight_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('goal', models.CharField(blank=True, choices=[('Muscle Building', 'Muscle Building'), ('Weight Loss', 'Weight Loss'), ('General Health', 'General Health')], max_length=100, null=True)),
                ('height_cm', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('is_injury', models.BooleanField(blank=True, null=True)),
                ('note_injury', models.CharField(blank=True, max_length=500, null=True)),
                ('note_sick', models.CharField(blank=True, max_length=500, null=True)),
                ('bio', models.CharField(blank=True, max_length=500, null=True)),
                ('weight_goal_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='update_at')),
                ('user', models.OneToOneField(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='player_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Player_Profiles',
            },
        ),
        migrations.CreateModel(
            name='CoachRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('created_at', models.DateTimeField(blank=True, db_column='creat_at', default=django.utils.timezone.now, null=True)),
                ('coach', models.ForeignKey(db_column='coach_id', on_delete=django.db.models.deletion.PROTECT, related_name='ratings', to='users.coachprofile')),
                ('player', models.ForeignKey(db_column='player_id', on_delete=django.db.models.deletion.PROTECT, related_name='given_ratings', to='users.playerprofile')),
            ],
            options={
                'db_table': 'Coach_ratings',
                'constraints': [models.UniqueConstraint(fields=('coach', 'player'), name='uq_coachrating_coach_player')],
            },
        ),
    ]
