# Generated by Django 6.0.6 on 2026-08-18 14:00

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_month', models.IntegerField()),
                ('name', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=18)),
                ('description', models.CharField(blank=True, max_length=500, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(blank=True, db_column='creat_at', default=django.utils.timezone.now, null=True)),
                ('coach', models.ForeignKey(db_column='coach_id', on_delete=django.db.models.deletion.CASCADE, related_name='packages', to='users.coachprofile')),
            ],
            options={
                'db_table': 'Subscription_Packages',
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform_percentage', models.DecimalField(blank=True, decimal_places=2, default=15, max_digits=5, null=True)),
                ('platform_profit', models.DecimalField(decimal_places=2, max_digits=10)),
                ('coach_profit', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_provider', models.CharField(blank=True, choices=[('stripe', 'Stripe')], default='stripe', max_length=50, null=True)),
                ('transaction_id', models.CharField(blank=True, max_length=255, null=True)),
                ('payment_status', models.CharField(blank=True, choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=50, null=True)),
                ('created_at', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('coach', models.ForeignKey(db_column='coach_id', on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='users.coachprofile')),
                ('player', models.ForeignKey(db_column='player_id', on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='users.playerprofile')),
                ('package', models.ForeignKey(db_column='package_id', on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='subscriptions.subscriptionpackage')),
            ],
            options={
                'db_table': 'Payments',
            },
        ),
        migrations.CreateModel(
            name='SubscriptionPlayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('finish', 'Finish')], default='active', max_length=50)),
                ('created_at', models.DateTimeField(blank=True, db_column='creat_at', default=django.utils.timezone.now, null=True)),
                ('package', models.ForeignKey(blank=True, db_column='package_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to='subscriptions.subscriptionpackage')),
                ('payment', models.ForeignKey(db_column='payments_id', on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to='subscriptions.payment')),
                ('player', models.ForeignKey(db_column='player_id', on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='users.playerprofile')),
            ],
            options={
                'db_table': 'Subscription_Player',
                'constraints': [models.UniqueConstraint(condition=models.Q(('status', 'active')), fields=('player',), name='unique_active_subscription_per_player')],
            },
        ),
    ]
