# Generated by Django 6.0.6 on 2026-08-18 14:00

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgramDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_day', models.PositiveSmallIntegerField()),
                ('name_day', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'Program_days',
            },
        ),
        migrations.CreateModel(
            name='ProgramDayExercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_id_exercise', models.IntegerField()),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('video_url', models.CharField(blank=True, max_length=255, null=True)),
                ('weight', models.DecimalField(db_column='weigth', decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0)])),
                ('sets', models.PositiveSmallIntegerField()),
                ('reps', models.PositiveSmallIntegerField()),
                ('program_day', models.ForeignKey(db_column='progame_day', on_delete=django.db.models.deletion.CASCADE, related_name='exercises', to='programs.programday')),
            ],
            options={
                'db_table': 'Program_days_exercises',
            },
        ),
        migrations.CreateModel(
            name='ProgramPlanExercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('start_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('end_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(blank=True, db_column='creat_at', default=django.utils.timezone.now, null=True)),
                ('coach', models.ForeignKey(db_column='coach_id', on_delete=django.db.models.deletion.PROTECT, related_name='program_plans', to='users.coachprofile')),
                ('player', models.ForeignKey(db_column='player_id', on_delete=django.db.models.deletion.PROTECT, related_name='program_plans', to='users.playerprofile')),
            ],
            options={
                'db_table': 'Program_Plans_Exercises',
            },
        ),
        migrations.CreateModel(
            name='ProgramWeek',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_week', models.IntegerField()),
                ('plan', models.ForeignKey(db_column='plan_id', on_delete=django.db.models.deletion.CASCADE, related_name='weeks', to='programs.programplanexercise')),
            ],
            options={
                'db_table': 'Program_Week',
            },
        ),
        migrations.AddField(
            model_name='programday',
            name='week',
            field=models.ForeignKey(db_column='week_id', on_delete=django.db.models.deletion.CASCADE, related_name='days', to='programs.programweek'),
        ),
        migrations.AddConstraint(
            model_name='programday',
            constraint=models.UniqueConstraint(fields=('number_day', 'week'), name='uq_programday_number_week'),
        ),
    ]
