# Generated by Django 6.0.6 on 2026-08-24 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='programplanexercise',
            name='updated_at',
            field=models.DateField(auto_now=True),
        ),
    ]
