# Generated by Django 6.0.6 on 2026-08-18 14:00

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NutritionPlanDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_day', models.PositiveSmallIntegerField()),
                ('name_day', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'Nutrition_plans_days',
            },
        ),
        migrations.CreateModel(
            name='NutritionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('start_at', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('end_at', models.DateTimeField()),
                ('note', models.CharField(blank=True, max_length=500, null=True)),
                ('calories_target', models.DecimalField(decimal_places=2, max_digits=18)),
                ('protein_target', models.DecimalField(decimal_places=2, max_digits=18)),
                ('carbs_target', models.DecimalField(decimal_places=2, max_digits=18)),
                ('fat_target', models.DecimalField(decimal_places=2, max_digits=18)),
                ('fiber_target', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(blank=True, db_column='creat_at', default=django.utils.timezone.now, null=True)),
                ('coach', models.ForeignKey(db_column='coach_id', on_delete=django.db.models.deletion.PROTECT, related_name='nutrition_plans', to='users.coachprofile')),
                ('player', models.ForeignKey(db_column='player_id', on_delete=django.db.models.deletion.CASCADE, related_name='nutrition_plans', to='users.playerprofile')),
            ],
            options={
                'db_table': 'Nutrition_plans',
            },
        ),
        migrations.CreateModel(
            name='NutritionPlanMeal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meal_number', models.PositiveSmallIntegerField()),
                ('name', models.CharField(default='Meal', max_length=100)),
                ('day', models.ForeignKey(db_column='day_id', on_delete=django.db.models.deletion.CASCADE, related_name='meals', to='nutritions.nutritionplanday')),
            ],
            options={
                'db_table': 'Nutrition_plans_meals',
            },
        ),
        migrations.CreateModel(
            name='MealFood',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_id_food', models.IntegerField()),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('quantity', models.CharField(max_length=50)),
                ('calories', models.DecimalField(decimal_places=2, max_digits=18, validators=[django.core.validators.MinValueValidator(0)])),
                ('protein', models.DecimalField(decimal_places=2, max_digits=18, validators=[django.core.validators.MinValueValidator(0)])),
                ('carbs', models.DecimalField(decimal_places=2, max_digits=18, validators=[django.core.validators.MinValueValidator(0)])),
                ('fat', models.DecimalField(decimal_places=2, max_digits=18, validators=[django.core.validators.MinValueValidator(0)])),
                ('fiber', models.DecimalField(decimal_places=2, default=0, max_digits=18, validators=[django.core.validators.MinValueValidator(0)])),
                ('plan_meal', models.ForeignKey(db_column='plan_meal_id', on_delete=django.db.models.deletion.CASCADE, related_name='foods', to='nutritions.nutritionplanmeal')),
            ],
            options={
                'db_table': 'Meals_foods',
            },
        ),
        migrations.CreateModel(
            name='NutritionPlanWeek',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_week', models.IntegerField()),
                ('plan', models.ForeignKey(db_column='plan_id', on_delete=django.db.models.deletion.CASCADE, related_name='weeks', to='nutritions.nutritionplan')),
            ],
            options={
                'db_table': 'Nutrition_plans_weeks',
            },
        ),
        migrations.AddField(
            model_name='nutritionplanday',
            name='week',
            field=models.ForeignKey(db_column='week_id', on_delete=django.db.models.deletion.CASCADE, related_name='days', to='nutritions.nutritionplanweek'),
        ),
        migrations.AddConstraint(
            model_name='nutritionplanmeal',
            constraint=models.UniqueConstraint(fields=('meal_number', 'day'), name='uq_nutritionmeal_number_day'),
        ),
        migrations.AddConstraint(
            model_name='nutritionplanday',
            constraint=models.UniqueConstraint(fields=('number_day', 'week'), name='uq_nutritionday_number_week'),
        ),
    ]
