# Generated by Django 6.0.6 on 2026-08-24 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutritions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='nutritionplan',
            name='updated_at',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='mealfood',
            name='api_id_food',
            field=models.CharField(max_length=100),
        ),
    ]
