# Generated by Django 6.0.6 on 2026-08-18 14:00

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('nutritions', '0001_initial'),
        ('programs', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BodyMeasurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('muscle_name', models.CharField(choices=[('chest', 'Chest'), ('waist', 'Waist'), ('hips', 'Hips'), ('biceps', 'Biceps'), ('thighs', 'Thighs'), ('other', 'Other')], max_length=50)),
                ('value_cm', models.DecimalField(decimal_places=1, max_digits=5)),
                ('date_day', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('player', models.ForeignKey(db_column='player_id', on_delete=django.db.models.deletion.CASCADE, related_name='body_measurements', to='users.playerprofile')),
            ],
            options={
                'db_table': 'Body_measurement',
            },
        ),
        migrations.CreateModel(
            name='DailyPhysicalHealth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight_kg', models.DecimalField(db_column='weigth_kg', decimal_places=2, max_digits=5)),
                ('energy_level', models.CharField(blank=True, choices=[('low', 'Low'), ('normal', 'Normal'), ('higth', 'High')], max_length=50, null=True)),
                ('muscle_soreness', models.CharField(blank=True, choices=[('none', 'None'), ('sore', 'Sore'), ('very sore', 'Very sore')], max_length=50, null=True)),
                ('note', models.CharField(blank=True, max_length=500, null=True)),
                ('date_day', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('player', models.ForeignKey(db_column='player_id', on_delete=django.db.models.deletion.CASCADE, related_name='daily_health', to='users.playerprofile')),
            ],
            options={
                'db_table': 'Daily_physical_health',
            },
        ),
        migrations.CreateModel(
            name='NutritionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('complete', 'Complete'), ('truant', 'Truant')], max_length=50)),
                ('date_day', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('calories_total', models.DecimalField(blank=True, decimal_places=0, max_digits=18, null=True)),
                ('protein', models.DecimalField(blank=True, decimal_places=0, max_digits=18, null=True)),
                ('carbs', models.DecimalField(blank=True, decimal_places=0, max_digits=18, null=True)),
                ('fat', models.DecimalField(blank=True, decimal_places=0, max_digits=18, null=True)),
                ('fiber', models.DecimalField(blank=True, decimal_places=0, max_digits=18, null=True)),
                ('meal', models.ForeignKey(blank=True, db_column='meal_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='logs', to='nutritions.nutritionplanmeal')),
            ],
            options={
                'db_table': 'Nutrition_logs',
            },
        ),
        migrations.CreateModel(
            name='WorkoutLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.CharField(blank=True, max_length=500, null=True)),
                ('status', models.CharField(choices=[('complete', 'Complete'), ('uncomplete', 'Uncomplete'), ('rest', 'Rest'), ('truant', 'Truant')], max_length=50)),
                ('date_day', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('program_day_exercise', models.ForeignKey(blank=True, db_column='program_day_exercise', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='workout_logs', to='programs.programdayexercise')),
            ],
            options={
                'db_table': 'Workout_logs',
            },
        ),
        migrations.CreateModel(
            name='WorkoutSetLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('set_number', models.PositiveSmallIntegerField()),
                ('reps', models.PositiveSmallIntegerField()),
                ('weight', models.DecimalField(decimal_places=2, max_digits=5)),
                ('workout_log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='set_logs', to='logs.workoutlog')),
            ],
            options={
                'db_table': 'Workout_set_logs',
                'constraints': [models.UniqueConstraint(fields=('workout_log', 'set_number'), name='uq_workoutsetlog_number')],
            },
        ),
    ]
