# Generated by Django 6.0.6 on 2026-08-26 12:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyphysicalhealth',
            name='weight_kg',
            field=models.DecimalField(db_column='weigth_kg', decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
