# Generated by Django 6.0.6 on 2026-08-26 12:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0002_alter_dailyphysicalhealth_weight_kg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bodymeasurement',
            name='value_cm',
            field=models.DecimalField(decimal_places=1, max_digits=5, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='workoutsetlog',
            name='weight',
            field=models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
