# Generated by Django 6.0.6 on 2026-08-18 14:00

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_task', models.CharField(blank=True, choices=[('Subscription reminder', 'Subscription reminder'), ('Acceptance of certificate', 'Acceptance of certificate'), ('Refusal of certificate', 'Refusal of certificate'), ('other', 'Other')], max_length=50, null=True)),
                ('transmission_channel', models.CharField(blank=True, choices=[('email', 'Email'), ('app', 'App')], max_length=50, null=True)),
                ('message', models.TextField(blank=True, null=True)),
                ('is_read', models.BooleanField(blank=True, default=False, null=True)),
                ('created_at', models.DateTimeField(blank=True, db_column='create_at', default=django.utils.timezone.now, null=True)),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Notifications',
            },
        ),
    ]
